# Netlify configuration file

[build]
  # Directory with the built frontend
  publish = "build"
  # Build command to create the React build and install function dependencies
  command = "CI=false npm run build && cd netlify/functions && npm install"

# Redirect API requests to the Netlify function
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Set environment variables
[build.environment]
  NODE_VERSION = "16"
  CI = "false"
  
# Special headers for security 
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 